// front/user/src/views/order/index.vue
<script lang="ts" setup>
import { onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import { createOrderAPI, getOrderListAPI } from '@/api/order'
import useScoket from '@/api/socket';

const orderList = ref([]);
const socket = useScoket('order')

const route = useRoute();

socket.on("haveNewOder", () => { })
const haveNewOder = async () => {
    socket.emit("haveNewOder", {
        message: "您有新的订单，请及时处理",
        orderList: orderList.value
    })
}

const getOrderList = async (orderId) => {
    const res = await getOrderListAPI(orderId)
    orderList.value = res
}

onMounted(() => {
    getOrderList(route.params.id)
})
</script>

<template>
    <div class="flex flex-col m-2 h-screen">
        <div class="flex justify-center items-center text-2xl font-bold mb-4">订单确认</div>
        <div class="flex-grow overflow-y-auto m-1 p-2">
            <div v-for="item in orderList" :key="item.id"
                class="flex flex-row justify-between items-center m-1 p-2 rounded-lg bg-slate-200">
                <div>
                    <div class="font-bold mx-1">{{ item.name }}</div>
                    <div class="mx-1">{{ item.quantity }}份</div>
                </div>

                <div class="font-bold mx-1 text-red-300">{{ item.price * item.quantity }}元</div>
            </div>
        </div>
        <div class="sticky bottom-0 bg-white p-4 border-t flex flex-col">
            <div class="flex justify-end">
                <el-button type="danger" @click="$router.back()">取消</el-button>
                <el-button type="primary" @click="haveNewOder">确认</el-button>
            </div>
        </div>
    </div>
</template>

// front/admin/src/pages/order/index.tsx
import { Button, Modal, Select } from "antd";
import useOrder from "../../hooks/order/useOrder";
export default function Order() {
	const {
		orderList,
		isOrderModalOpen,
		orderDetail,
		orderOptions,
		getOrderStatus,
		handOrderleCancel,
		handOrderleOk,
		showOrderModal,
		orderSelectChange,
	} = useOrder();
	return (
		<div className="flex flex-col h-screen">
			<div className="flex flex-row items-center justify-center p-2 font-bold text-2xl">
				订单管理
			</div>
			<div className="flex flex-row items-center justify-center p-2">
				<Select
					className="w-96 h-8"
					mode="multiple"
					allowClear
					placeholder="查询订单类型"
					defaultValue={[]}
					onChange={orderSelectChange}
					options={orderOptions}
				/>
			</div>
			{orderList.map((item) => (
				<div
					className="flex justify-between items-center p-2 border-b-2 min-h-16 overflow-y-auto"
					key={item.id}
				>
					<div>
						<div className="mx-1">订单编号：{item.id}</div>
						<div className="mx-1">订单金额：{item.totalPrice}</div>
						<div className="mx-1 font-bold">
							订单状态：{getOrderStatus(item.orderStatus)}
						</div>
					</div>
					<div>
						<Button
							className="mx-1"
							type="primary"
							onClick={() => showOrderModal(item.id)}
						>
							订单详情
						</Button>
						<Button>订单修改</Button>
					</div>
				</div>
			))}
			<Modal
				title="订单详情"
				open={isOrderModalOpen}
				onOk={handOrderleOk}
				onCancel={handOrderleCancel}
			>
				<div className="flex flex-col">
					<div className="flex flex-col  justify-between">
						{orderDetail.map((item) => (
							<div className="bg-slate-200 m-1 p-2 rounded-xl">
								<div>菜品：{item.name}</div>
								<div>数量：{item.quantity}份</div>
							</div>
						))}
					</div>
				</div>
			</Modal>
		</div>
	);
}
