// front/user/src/views/layout/index.vue
<script setup>
import headerBar from './component/headerBar.vue';
import sideBar from './component/sideBar.vue';
import bottomBar from './component/bottomBar.vue';
</script>
<template>
    <div class="flex flex-col h-screen">
        <headerBar class="hidden md:block"></headerBar>
        <div class="flex flex-row overflow-hidden">
            <sideBar class="basis-1/6 hidden md:block"></sideBar>
            <div class="md:w-5/6  w-screen">
                <!-- 使用 overflow-y-auto 允许垂直滚动 -->
                <router-view></router-view>
            </div>
        </div>
        <bottomBar class="sm:block md:hidden"></bottomBar>
    </div>
</template>

// front/admin/src/layout/index.tsx
import Bottombar from "./bottombar";
import Sidebar from "./sidebar";
import { Outlet } from "react-router-dom";
export default function layout() {
	return (
		<div className="flex flex-col">
			<div className="flex flex-row h-screen overflow-hidden">
				<div className="hidden md:block md:basis-1/6 flex-col bg-red-300">
					<Sidebar />
				</div>
				<div className="flex-1 flex-col md:basis-5/6 bg-blue-300 overflow-auto">
					<Outlet />
				</div>
			</div>

			{/* <div className="block md:hidden h-1/6">
				<Bottombar />
			</div> */}
		</div>
	);
}
