// front/user/src/views/auth/login/index.vue
<script setup lang="ts">
import type { LoginInfo } from '@/dto/userInfo';
import { ref } from 'vue';
import { useUserStore } from '@/stores/userstore';

const labelposition = ref('right')
const circleUrl = ref('https://cube.elemecdn.com/3/7c/3ea6beec64369c2642b92c6726f1epng.png')

const userStore = useUserStore()

const loginInfo = ref<LoginInfo>({
    loginId: null,
    password: null
})

const login = (loginInfo: LoginInfo) => {
    userStore.getUserInfo(loginInfo)
}

</script>

<template>
    <div class="flex flex-row justify-center items-center h-screen">
        <div class="flex flex-col justify-center bg-transblue rounded-lg shadow-2xl p-8">
            <div class="flex text-3xl font-bold mb-4 justify-center items-center">
                <el-avatar :size="50" :src="circleUrl" />
                <span class="ml-2">用户登录</span>
            </div>
            <el-form :label-position=labelposition label-width="auto" :model=loginInfo style="max-width: 800px">
                <el-form-item label="登录id" :label-position=labelposition>
                    <el-input v-model="loginInfo.loginId" />
                </el-form-item>
                <el-form-item label="密码" :label-position=labelposition>
                    <el-input v-model="loginInfo.password" type="password" />
                </el-form-item>
            </el-form>
            <div class="flex justify-center items-center">
                <el-button type="primary" @click="login(loginInfo)">登录</el-button>
            </div>
            <div class="flex justify-center items-center mt-4">
                <span>没有账号？</span>
                <router-link to="/auth/register" class="ml-2 text-transpink hover:underline">立即注册</router-link>
            </div>
        </div>
    </div>
</template>

// front/admin/src/pages/login/index.tsx
import { Button, Form, Input } from "antd";
import useLogin from "../../hooks/login/uselogin";
import { NavLink } from "react-router-dom";

export default function Login() {
	const { onFinish, onFinishFailed } = useLogin();
	const logoImg =
		"https://upload.wikimedia.org/wikipedia/commons/1/1a/Dolby_logo_2019.svg";

	return (
		<div className="flex justify-center items-center h-screen">
			<div className="flex flex-col items-center p-6 md:p-10 lg:p-15 rounded-lg card shadow-2xl bg-gradient-to-r from-transblue to-transpink">
				<div className="flex items-center mb-4">
					<div className="mr-2 md:m-3 lg:m-8 hidden md:block">
						<img src={logoImg} alt="logo" className="w-12 h-10" />
					</div>
					<Form
						name="basic"
						labelCol={{
							span: 8,
						}}
						wrapperCol={{
							span: 16,
						}}
						style={{
							maxWidth: 600,
						}}
						initialValues={{
							remember: true,
						}}
						onFinish={onFinish}
						onFinishFailed={onFinishFailed}
						autoComplete="off"
					>
						<Form.Item
							label="用户id"
							name="loginId"
							rules={[
								{
									required: true,
									message: "请输入你的用户id",
								},
							]}
						>
							<Input />
						</Form.Item>

						<Form.Item
							label="密码"
							name="password"
							rules={[
								{
									required: true,
									message: "请输入你的密码",
								},
							]}
						>
							<Input.Password />
						</Form.Item>

						<Form.Item
							wrapperCol={{
								offset: 8,
								span: 16,
							}}
						>
							<Button type="primary" htmlType="submit">
								登录
							</Button>
						</Form.Item>
					</Form>
				</div>
				<NavLink
					to={"/auth/register"}
					className={"text-sm text-blue-400"}
				>
					还没注册？
				</NavLink>
			</div>
		</div>
	);
}
